dist: trusty
sudo: false

language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "dciAf3dxYkhg68sMTXCSyxt3c4M9hMBup9cgxt6NJHnPyp0P/w1xYdi0uIX+XaZY8V0N4Cg2P1lmWykvmkiPkOMTK0sRaDyPalvQowf8zrTeyybDLShIcrBWipIlKQ1ZXT4MUDlmtCXtVI1geGNwqze8htS/PYywV6j8uE96Y7SP3255UqHSYirlB3AiM97BcRkLLaAFaDQwadSkPoMDdwD2sGhxweB6VBrJclAQWvBAJtdJ84LyGuI5gE47WGYGNd9FCoCvcWy2AW/oQVYn7WSIG/ZWiBXSR9OQQE5XGv2yJ/uu/A36Xn35/830Krs35LRPHnZj1Ua0v2g8zuImpefxb0zOgIV6JCj2zZ3DphsQDyA9uTbamaU0UgIEYmtemgGcU3hMeAWmndAEQj3G3e6mkIC+RCtY37xmfvu3EXV4yoad1YeMan+7Ccru8xkc8BOFcujw/bv27KQulKzeX+FeY2bMXGjxSO8hBgEZOeoH7KjDMKm4nt074MKgWtaS3mHC7qJVkvjzhZLXUUmi6V2Ln0AlWYsbiaOqeWbaj4vTG+ePY5LiS1BXLRUhV3pYo6EQK1+Nkn4YFKvIPE9VV3m20gHvrMxLGUOFuOb4N4u4dTLonjRVNkU5ZboqisMxYAY5ej9hhXiAwm9QoCxx+lw+/FaXe/1uaXXZtwUtAiE="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete